[package]
name = "savemail"
version = "0.1.0"
authors = ["Daniel Dabek <xordaniel@gmail.com>"]

[dependencies]
postgres = "0.15"
router = "0.5.1"
iron = "0.5.1"
serde_json = "1.0"
serde = "*"
serde_derive = "*"
iron-cors = "*"
unicase = "1.3.0"